---
name: Game-of-life
variables:
        - name: hai
          value: world
stages:
        - stage: Build
          jobs:
                  - job: mavncompile
                    steps:
                            - task: Maven@3
                              inputs:
                                      mavenPomFile: 'pom.xml'
                                      goals: 'compile'
                                      publishJUnitResults: true
                                      testResultsFiles: '**/surefire-reports/TEST-*.xml'
                                      jdkVersionOption: 'default'
