---
name: my-gol-pipeine-new
variables:
        - name: var1
          value: hello
        - name: var2
          value: rk
stages:
        - stage: 'mavencompile'
          jobs:
          pool: my_agent_pool
                  - job: 'compile job'
                    steps:
                            - task: Maven@3
                              inputs:
                                      mavenPomFile: 'pom.xml'
                                      goals: 'compile'
                                      publishJUnitResults: true
                                      testResultsFiles: '**/surefire-reports/TEST-*.xml'
                                      dkVersionOption: 'default'
                            - script: echo $(var1) $(var2)
        - stage: 'package'
          jobs:
          pool: my_agent_pool
                - job: package
                  steps:
                          - task: Maven@3
                            inputs:
                                      mavenPomFile: 'pom.xml'
                                      goals: 'package'
                                      publishJUnitResults: true
                                      testResultsFiles: '**/*war'
                                      dkVersionOption: 'default'

